# Generated by Django 3.2.4 on 2021-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_photo',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
