# Generated by Django 3.2.4 on 2021-07-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0003_auto_20210705_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_model',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_amt', models.FloatField()),
                ('txn_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
