# Generated by Django 3.2.4 on 2021-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210708_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_model',
            name='txn_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
