# Generated by Django 3.2.4 on 2021-07-13 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_waterpoint_water_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0005_alter_transaction_model_txn_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward_model',
            fields=[
                ('rew_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rew_amt', models.FloatField()),
                ('rew_status', models.CharField(default='none', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descripton', models.CharField(default='No description available', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='addmoney_model',
            fields=[
                ('addmoney_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_amount', models.FloatField()),
                ('order_currency', models.CharField(max_length=20)),
                ('adm_status', models.CharField(default='none', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
