# Generated by Django 3.2.4 on 2021-07-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_mac',
            field=models.CharField(default='', max_length=100),
        ),
    ]
