# Generated by Django 3.2.4 on 2021-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210705_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_type_availaable',
            name='credit_rate',
            field=models.FloatField(null=True),
        ),
    ]
