# Generated by Django 3.2.4 on 2021-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_device_type_availaable_credit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpoint',
            name='water_rate',
            field=models.FloatField(null=True),
        ),
    ]
