# Generated by Django 3.2.4 on 2021-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='service_provider',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
