# Generated by Django 3.2.4 on 2021-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_service_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='activation_status',
            new_name='agent_is_active',
        ),
    ]
