# Generated by Django 3.2.4 on 2021-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rename_activation_status_agent_agent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='balance_amount',
            field=models.FloatField(default=0),
        ),
    ]
